services:
  accounts-service:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    networks:
      - backend

  loans-service:
    build:
      context: ./loans
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    networks:
      - backend

  cards-service:
    build:
      context: ./cards
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
